[package]
name = "countdown_solver"
version = "0.1.0"
authors = ["rtpike <impressive.rtpike@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
threadpool = "1.8.1"